version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.33.3
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/data
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - nginx-proxy_default
      - internal
    environment:
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST: example.com
      LETSENCRYPT_EMAIL: webmaster@example.com
    restart: unless-stopped
    depends_on:
      - cadvisor

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    networks:
      - internal
      - nginx-proxy_default
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - "--housekeeping_interval=30s"
      - "--docker_only=true"
      - "--enable_metrics=memory,cpu,network,disk"
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:v1.5.0
    command:
      - "--path.rootfs=/host"
    networks:
      - internal
      - nginx-proxy_default
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"

networks:
  internal:
  nginx-proxy_default:
    external: true
