version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.33.3
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    networks:
      - nginx-proxy_default
      - internal
    environment:
      VIRTUAL_HOST: example.com
      LETSENCRYPT_HOST: example.com
      LETSENCRYPT_EMAIL: webmaster@example.com
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:v1.3.1
    command:
      - "--path.rootfs=/host"
    networks:
      - internal
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"

  cadvisor:
    image: google/cadvisor:v0.33.0
    networks:
      - internal
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/var/lib/docker:ro

networks:
  internal:
  nginx-proxy_default:
    external: true
