global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
#  - "some.rules"

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: node_exporter
    static_configs:
      - targets: ['node_exporter:9100']
